package com.example.ui.screens

import kotlin.math.roundToInt
import androidx.compose.animation.*
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.material.icons.filled.Build

import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Analytics
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.History
import androidx.compose.material.icons.filled.ExpandMore
import androidx.compose.material.icons.filled.ExpandLess
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.Shuffle
import androidx.compose.material.icons.filled.Person
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.components.FrostedMeshBackground
import com.example.ui.components.GlassyCard
import com.example.ui.components.JokerCard
import com.example.ui.components.JokerRotationSection
import com.example.ui.components.NeonButton
import com.example.ui.theme.CrimsonHot
import com.example.ui.theme.FuchsiaAccent
import com.example.ui.theme.GoldStar
import com.example.ui.theme.IndigoAccent
import com.example.ui.theme.NeonBlue
import com.example.ui.theme.NeonGreen
import com.example.ui.viewmodel.AppViewModel
import java.text.SimpleDateFormat
import java.util.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TeamConfigScreen(viewModel: AppViewModel) {
    val numberOfTeams by viewModel.configNumberOfTeams.collectAsState()
    val configState by viewModel.teamConfigState.collectAsState()
    val playersList by viewModel.buildPlayersList.collectAsState()
    val generatedTeams by viewModel.generatedTeams.collectAsState()
    val jokerPlayer by viewModel.jokerPlayer.collectAsState()
    val remainingJokerCandidates by viewModel.remainingJokerCandidates.collectAsState()
    val previousJokersHistory by viewModel.previousJokersHistory.collectAsState()
    val sessionHistory by viewModel.sessionHistory.collectAsState()
    val uniqueTeamsGenerated by viewModel.uniqueTeamsGenerated.collectAsState()
    val duplicatesPrevented by viewModel.duplicatesPrevented.collectAsState()
    val currentShuffleNumber by viewModel.currentShuffleNumber.collectAsState()
    val isGenerating by viewModel.isGeneratingCandidates.collectAsState()
    val generationProgress by viewModel.candidateGenerationProgress.collectAsState()
    val generationTarget by viewModel.candidateGenerationTarget.collectAsState()
    val generationDiagnostics by viewModel.generationDiagnostics.collectAsState()
    val pairStats by viewModel.pairStatistics.collectAsState()
    val candidatePairAnalysis by viewModel.candidatePairAnalysis.collectAsState()
    val candidateOpponentAnalysis by viewModel.candidateOpponentAnalysis.collectAsState()
    val fairnessScore by viewModel.currentFairnessScore.collectAsState()
    val fairnessRating by viewModel.currentFairnessRating.collectAsState()
    val candidateFairnessEvaluation by viewModel.candidateFairnessEvaluation.collectAsState()
    val candidatesEvaluatedCount by viewModel.candidatesEvaluatedCount.collectAsState()
    val bestFairnessScore by viewModel.bestFairnessScore.collectAsState()
    val opponentStats by viewModel.opponentStatistics.collectAsState()
    val currentStrengthAnalysis by viewModel.currentStrengthAnalysis.collectAsState()
    val qualityResult by viewModel.candidateQualityResult.collectAsState()
    val additionalAttempts by viewModel.additionalGenerationAttempts.collectAsState()

    var showWhyThisTeamExplanation by remember { mutableStateOf(false) }

    FrostedMeshBackground {
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(horizontal = 20.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            item {
                Spacer(modifier = Modifier.height(24.dp))
                Text(
                    text = "TEAM CONFIGURATION",
                    style = MaterialTheme.typography.titleSmall.copy(
                        color = IndigoAccent,
                        fontWeight = FontWeight.Bold,
                        letterSpacing = 2.sp
                    )
                )
                Text(
                    text = "Configure how your active roster is divided",
                    style = MaterialTheme.typography.bodySmall,
                    color = Color.LightGray
                )
                Spacer(modifier = Modifier.height(8.dp))
            }

            // Number of Teams Input Card
            item {
                GlassyCard(
                    modifier = Modifier.fillMaxWidth(),
                    cornerRadius = 24
                ) {
                    Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.SpaceBetween,
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Icon(
                                    imageVector = Icons.Default.Person,
                                    contentDescription = "Teams",
                                    tint = IndigoAccent,
                                    modifier = Modifier.size(24.dp)
                                )
                                Spacer(modifier = Modifier.width(8.dp))
                                Text(
                                    text = "Split Roster Into",
                                    style = MaterialTheme.typography.titleMedium.copy(
                                        fontWeight = FontWeight.Bold,
                                        color = Color.White
                                    )
                                )
                            }
                            
                            // Active Players Badge
                            Box(
                                modifier = Modifier
                                    .clip(RoundedCornerShape(8.dp))
                                    .background(NeonBlue.copy(alpha = 0.15f))
                                    .border(1.dp, NeonBlue.copy(alpha = 0.3f), RoundedCornerShape(8.dp))
                                    .padding(horizontal = 10.dp, vertical = 6.dp)
                            ) {
                                Text(
                                    text = "${playersList.size} Active Players",
                                    color = NeonBlue,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 12.sp
                                )
                            }
                        }

                        HorizontalDivider(color = Color.White.copy(alpha = 0.08f))

                        OutlinedTextField(
                            value = numberOfTeams,
                            onValueChange = { viewModel.updateConfigNumberOfTeams(it) },
                            label = { Text("Number of Teams") },
                            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                            colors = OutlinedTextFieldDefaults.colors(
                                focusedTextColor = Color.White,
                                unfocusedTextColor = Color.White,
                                focusedBorderColor = IndigoAccent,
                                unfocusedBorderColor = Color.White.copy(alpha = 0.12f),
                                focusedLabelColor = IndigoAccent,
                                unfocusedLabelColor = Color.Gray
                            ),
                            modifier = Modifier.fillMaxWidth().testTag("number_of_teams_input"),
                            singleLine = true
                        )
                    }
                }
            }

            // Calculation Preview Card
            item {
                GlassyCard(
                    modifier = Modifier.fillMaxWidth(),
                    cornerRadius = 24
                ) {
                    Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
                        Text(
                            text = "PREVIEW",
                            style = MaterialTheme.typography.labelSmall,
                            color = Color.Gray,
                            fontWeight = FontWeight.Bold
                        )

                        AnimatedVisibility(
                            visible = configState.error != null,
                            enter = fadeIn() + expandVertically(),
                            exit = fadeOut() + shrinkVertically()
                        ) {
                            Box(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .clip(RoundedCornerShape(12.dp))
                                    .background(CrimsonHot.copy(alpha = 0.1f))
                                    .border(1.dp, CrimsonHot.copy(alpha = 0.3f), RoundedCornerShape(12.dp))
                                    .padding(16.dp)
                            ) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Icon(
                                        imageVector = Icons.Default.Person,
                                        contentDescription = "Error",
                                        tint = CrimsonHot
                                    )
                                    Spacer(modifier = Modifier.width(12.dp))
                                    Text(
                                        text = configState.error ?: "",
                                        color = CrimsonHot,
                                        style = MaterialTheme.typography.bodyMedium,
                                        fontWeight = FontWeight.Bold
                                    )
                                }
                            }
                        }

                        AnimatedVisibility(
                            visible = configState.error == null,
                            enter = fadeIn() + expandVertically(),
                            exit = fadeOut() + shrinkVertically()
                        ) {
                            Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                                // Players per team
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .clip(RoundedCornerShape(12.dp))
                                        .background(NeonGreen.copy(alpha = 0.05f))
                                        .border(1.dp, NeonGreen.copy(alpha = 0.2f), RoundedCornerShape(12.dp))
                                        .padding(16.dp)
                                ) {
                                    Row(verticalAlignment = Alignment.CenterVertically) {
                                        Icon(Icons.Default.Info, contentDescription = "Info", tint = NeonGreen)
                                        Spacer(modifier = Modifier.width(12.dp))
                                        Text(
                                            text = "Players Per Team",
                                            color = Color.LightGray,
                                            style = MaterialTheme.typography.bodyMedium
                                        )
                                    }
                                    Text(
                                        text = "${configState.playersPerTeam}",
                                        color = NeonGreen,
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold
                                    )
                                }

                                // Remaining Players
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .clip(RoundedCornerShape(12.dp))
                                        .background(if (configState.remainingPlayers > 0) GoldStar.copy(alpha = 0.05f) else Color.White.copy(alpha = 0.02f))
                                        .border(1.dp, if (configState.remainingPlayers > 0) GoldStar.copy(alpha = 0.2f) else Color.White.copy(alpha = 0.05f), RoundedCornerShape(12.dp))
                                        .padding(16.dp)
                                ) {
                                    Row(verticalAlignment = Alignment.CenterVertically) {
                                        Icon(
                                            Icons.Default.Info, 
                                            contentDescription = "Info", 
                                            tint = if (configState.remainingPlayers > 0) GoldStar else Color.Gray
                                        )
                                        Spacer(modifier = Modifier.width(12.dp))
                                        Text(
                                            text = "Remaining Substitutes",
                                            color = Color.LightGray,
                                            style = MaterialTheme.typography.bodyMedium
                                        )
                                    }
                                    Text(
                                        text = "${configState.remainingPlayers}",
                                        color = if (configState.remainingPlayers > 0) GoldStar else Color.Gray,
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold
                                    )
                                }
                            }
                        }
                    }
                }
            }

            // Shuffle Button Item
            item {
                AnimatedVisibility(
                    visible = configState.error == null,
                    enter = fadeIn() + expandVertically(),
                    exit = fadeOut() + shrinkVertically()
                ) {
                    if (isGenerating) {
                        GlassyCard(
                            modifier = Modifier.fillMaxWidth(),
                            cornerRadius = 16
                        ) {
                            Column(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(16.dp),
                                horizontalAlignment = Alignment.CenterHorizontally
                            ) {
                                CircularProgressIndicator(color = NeonGreen)
                                Spacer(modifier = Modifier.height(16.dp))
                                Text("Generating Teams...", color = NeonGreen, fontWeight = FontWeight.Bold)
                                Text("$generationProgress / $generationTarget Candidates", color = Color.White, fontSize = 12.sp)
                            }
                        }
                    } else {
                        NeonButton(
                            text = if (generatedTeams.isEmpty()) "Shuffle & Generate Teams" else "Shuffle Again",
                            onClick = { viewModel.shuffleTeams() },
                            modifier = Modifier
                                .fillMaxWidth()
                                .testTag("shuffle_again_button"),
                            glowingColor = NeonGreen
                        )
                    }
                }
            }

            // Shuffle Summary & Fairness Ranking Card
            val analysis = candidatePairAnalysis
            if (analysis != null) {
                item {
                    GlassyCard(
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("shuffle_summary_card"),
                        cornerRadius = 16
                    ) {
                        Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                            // Header: Fairness Score & Rating Badge
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Icon(
                                        imageVector = Icons.Default.Analytics,
                                        contentDescription = "Fairness Engine",
                                        tint = NeonBlue,
                                        modifier = Modifier.size(20.dp)
                                    )
                                    Spacer(modifier = Modifier.width(8.dp))
                                    Text(
                                        text = "COMBINED FAIRNESS SCORE",
                                        style = MaterialTheme.typography.labelMedium,
                                        color = NeonBlue,
                                        fontWeight = FontWeight.Bold,
                                        letterSpacing = 1.sp
                                    )
                                }
                                val isBestAvailable = qualityResult?.qualityLabel == com.example.util.FairnessQualityLabel.BEST_AVAILABLE
                                val badgeText = if (isBestAvailable) "BEST AVAILABLE" else if (qualityResult?.passed == true) "✓ TARGET MET" else fairnessRating.uppercase()
                                val ratingColor = if (isBestAvailable) GoldStar else when (fairnessRating) {
                                    "Excellent", "Very Good" -> NeonGreen
                                    "Good" -> NeonBlue
                                    "Average" -> GoldStar
                                    else -> FuchsiaAccent
                                }
                                Text(
                                    text = badgeText,
                                    fontSize = 11.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = ratingColor,
                                    modifier = Modifier
                                        .clip(RoundedCornerShape(6.dp))
                                        .background(ratingColor.copy(alpha = 0.15f))
                                        .padding(horizontal = 8.dp, vertical = 4.dp)
                                        .testTag("fairness_rating")
                                )
                            }
                            
                            // Score Display
                            Column(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.Center
                            ) {
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.Center
                                ) {
                                    val ratingColor = if (qualityResult?.qualityLabel == com.example.util.FairnessQualityLabel.BEST_AVAILABLE) GoldStar else when (fairnessRating) {
                                        "Excellent", "Very Good" -> NeonGreen
                                        "Good" -> NeonBlue
                                        "Average" -> GoldStar
                                        else -> FuchsiaAccent
                                    }
                                    Text(
                                        text = "$fairnessScore",
                                        style = MaterialTheme.typography.displayMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = ratingColor,
                                        modifier = Modifier.testTag("fairness_score")
                                    )
                                    Text(
                                        text = "/100",
                                        style = MaterialTheme.typography.titleMedium,
                                        color = Color.Gray,
                                        modifier = Modifier.align(Alignment.Bottom).padding(bottom = 8.dp)
                                    )
                                }
                                if (qualityResult?.qualityLabel == com.example.util.FairnessQualityLabel.BEST_AVAILABLE) {
                                    Text(
                                        text = "Best available arrangement found. No generated arrangement met all fairness thresholds.",
                                        fontSize = 11.sp,
                                        color = GoldStar,
                                        fontWeight = FontWeight.SemiBold
                                    )
                                }
                            }

                            // Component Breakdown Grid (Teammate 40%, Opponent 20%, Team Balance 30%, Joker 10%)
                            candidateFairnessEvaluation?.let { eval ->
                                HorizontalDivider(color = Color.White.copy(alpha = 0.08f))
                                Text(
                                    text = "FAIRNESS BREAKDOWN",
                                    style = MaterialTheme.typography.labelSmall,
                                    color = Color.Gray,
                                    fontWeight = FontWeight.Bold
                                )
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    Column(horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.weight(1f)) {
                                        Text("${eval.teammateScore.roundToInt()}", style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold, color = NeonGreen)
                                        Text("Teammates (40%)", style = MaterialTheme.typography.labelSmall, color = Color.Gray, fontSize = 9.sp)
                                    }
                                    Column(horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.weight(1f)) {
                                        Text("${eval.opponentScore.roundToInt()}", style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold, color = NeonBlue)
                                        Text("Opponents (20%)", style = MaterialTheme.typography.labelSmall, color = Color.Gray, fontSize = 9.sp)
                                    }
                                    Column(horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.weight(1f)) {
                                        Text("${eval.strengthScore.roundToInt()}", style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold, color = GoldStar)
                                        Text("Balance (30%)", style = MaterialTheme.typography.labelSmall, color = Color.Gray, fontSize = 9.sp)
                                    }
                                    Column(horizontalAlignment = Alignment.CenterHorizontally, modifier = Modifier.weight(1f)) {
                                        Text("${eval.jokerScore.roundToInt()}", style = MaterialTheme.typography.titleSmall, fontWeight = FontWeight.Bold, color = FuchsiaAccent)
                                        Text("Joker (10%)", style = MaterialTheme.typography.labelSmall, color = Color.Gray, fontSize = 9.sp)
                                    }
                                }
                            }
                            
                            HorizontalDivider(color = Color.White.copy(alpha = 0.08f))

                            // Expandable "Why this team?" Explanation Section
                            Column(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .clip(RoundedCornerShape(12.dp))
                                    .background(Color.White.copy(alpha = 0.03f))
                                    .border(1.dp, Color.White.copy(alpha = 0.06f), RoundedCornerShape(12.dp))
                                    .padding(12.dp)
                            ) {
                                Row(
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .clickable { showWhyThisTeamExplanation = !showWhyThisTeamExplanation }
                                        .testTag("why_this_team_toggle"),
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    Row(verticalAlignment = Alignment.CenterVertically) {
                                        Icon(
                                            imageVector = Icons.Default.Info,
                                            contentDescription = "Why this team",
                                            tint = NeonGreen,
                                            modifier = Modifier.size(16.dp)
                                        )
                                        Spacer(modifier = Modifier.width(8.dp))
                                        Text(
                                            text = "Why this team?",
                                            style = MaterialTheme.typography.labelMedium,
                                            fontWeight = FontWeight.Bold,
                                            color = Color.White
                                        )
                                    }
                                    Icon(
                                        imageVector = if (showWhyThisTeamExplanation) Icons.Default.ExpandLess else Icons.Default.ExpandMore,
                                        contentDescription = "Toggle explanation",
                                        tint = Color.Gray
                                    )
                                }

                                AnimatedVisibility(
                                    visible = showWhyThisTeamExplanation,
                                    enter = fadeIn() + expandVertically(),
                                    exit = fadeOut() + shrinkVertically()
                                ) {
                                    Column(
                                        modifier = Modifier.padding(top = 10.dp),
                                        verticalArrangement = Arrangement.spacedBy(6.dp)
                                    ) {
                                        if (qualityResult?.qualityLabel == com.example.util.FairnessQualityLabel.BEST_AVAILABLE) {
                                            Text(
                                                text = "Best Available Arrangement",
                                                fontWeight = FontWeight.Bold,
                                                color = GoldStar,
                                                fontSize = 11.sp
                                            )
                                            Text(
                                                text = "Why it could not meet the target:",
                                                fontSize = 11.sp,
                                                color = Color.LightGray,
                                                fontWeight = FontWeight.SemiBold
                                            )
                                            qualityResult?.failedChecks?.forEach { failedMsg ->
                                                Text(
                                                    text = "• $failedMsg",
                                                    fontSize = 11.sp,
                                                    color = GoldStar
                                                )
                                            }
                                            Text(
                                                text = "Additional arrangements checked: $candidatesEvaluatedCount",
                                                fontSize = 11.sp,
                                                color = Color.Gray
                                            )
                                        } else {
                                            Text(
                                                text = "✓ Target fairness thresholds satisfied",
                                                fontSize = 11.sp,
                                                color = NeonGreen,
                                                fontWeight = FontWeight.Bold
                                            )
                                        }
                                        Text(
                                            text = "✓ Unique arrangement signature verified (No duplicate layout)",
                                            fontSize = 11.sp,
                                            color = Color.LightGray
                                        )
                                        Text(
                                            text = "✓ ${analysis.newPairs} new teammate relationship pairs created",
                                            fontSize = 11.sp,
                                            color = NeonGreen
                                        )
                                        if (analysis.repeatedPairs > 0) {
                                            Text(
                                                text = "✓ ${analysis.repeatedPairs} repeated teammate pairs (minimized penalty)",
                                                fontSize = 11.sp,
                                                color = GoldStar
                                            )
                                        } else {
                                            Text(
                                                text = "✓ Zero repeated teammate pairs in current arrangement",
                                                fontSize = 11.sp,
                                                color = NeonGreen
                                            )
                                        }
                                        currentStrengthAnalysis?.let { str ->
                                            Text(
                                                text = "✓ Team strength difference minimized to ${str.strengthDifference} (Avg rating: ${String.format(java.util.Locale.US, "%.1f", str.averageTeamStrength)})",
                                                fontSize = 11.sp,
                                                color = NeonBlue
                                            )
                                        }
                                        jokerPlayer?.let { joker ->
                                            Text(
                                                text = "✓ Joker ($joker) assigned following fair cycle rotation rules",
                                                fontSize = 11.sp,
                                                color = FuchsiaAccent
                                            )
                                        }
                                        Text(
                                            text = "✓ Ranked #1 out of $candidatesEvaluatedCount generated candidates",
                                            fontSize = 11.sp,
                                            color = Color.White,
                                            fontWeight = FontWeight.Bold
                                        )
                                    }
                                }
                            }

                            HorizontalDivider(color = Color.White.copy(alpha = 0.08f))

                            // Stats Grid: Candidates Evaluated, Best Score, Duplicates, Unique Teams
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceEvenly,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                    Text(if (currentShuffleNumber > 0) "#$currentShuffleNumber" else "-", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold, color = Color.White)
                                    Text("Shuffle No.", style = MaterialTheme.typography.labelSmall, color = Color.Gray, fontSize = 9.sp)
                                }
                                HorizontalDivider(modifier = Modifier.height(28.dp).width(1.dp), color = Color.White.copy(alpha = 0.1f))
                                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                    Text("$candidatesEvaluatedCount", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold, color = NeonBlue)
                                    Text("Evaluated", style = MaterialTheme.typography.labelSmall, color = Color.Gray, fontSize = 9.sp)
                                }
                                HorizontalDivider(modifier = Modifier.height(28.dp).width(1.dp), color = Color.White.copy(alpha = 0.1f))
                                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                    Text("$uniqueTeamsGenerated", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold, color = NeonGreen)
                                    Text("Unique Teams", style = MaterialTheme.typography.labelSmall, color = Color.Gray, fontSize = 9.sp)
                                }
                                HorizontalDivider(modifier = Modifier.height(28.dp).width(1.dp), color = Color.White.copy(alpha = 0.1f))
                                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                    Text("$duplicatesPrevented", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold, color = if (duplicatesPrevented > 0) GoldStar else Color.LightGray)
                                    Text("Duplicates", style = MaterialTheme.typography.labelSmall, color = Color.Gray, fontSize = 9.sp)
                                }
                                HorizontalDivider(modifier = Modifier.height(28.dp).width(1.dp), color = Color.White.copy(alpha = 0.1f))
                                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                    Text("${bestFairnessScore.roundToInt()}%", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold, color = NeonGreen)
                                    Text("Best Score", style = MaterialTheme.typography.labelSmall, color = Color.Gray, fontSize = 9.sp)
                                }
                            }
                        }
                    }
                }
            }

            // Developer Debug Section (Collapsible)
            if (generationDiagnostics != null) {
                item {
                    val diag = generationDiagnostics!!
                    var isDebugExpanded by remember { androidx.compose.runtime.mutableStateOf(false) }
                    GlassyCard(
                        modifier = Modifier.fillMaxWidth().padding(top = 8.dp),
                        cornerRadius = 16
                    ) {
                        Column(
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .clickable { isDebugExpanded = !isDebugExpanded }
                                    .padding(16.dp),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Icon(Icons.Default.Build, contentDescription = "Diagnostics", tint = NeonGreen, modifier = Modifier.size(16.dp))
                                    Spacer(modifier = Modifier.width(6.dp))
                                    Text("Developer Debug Mode", color = NeonGreen, fontWeight = FontWeight.Bold, fontSize = 12.sp)
                                }
                                Icon(
                                    imageVector = if (isDebugExpanded) Icons.Default.ExpandLess else Icons.Default.ExpandMore,
                                    contentDescription = "Expand/Collapse",
                                    tint = NeonGreen
                                )
                            }
                            
                            AnimatedVisibility(visible = isDebugExpanded) {
                                Column(
                                    modifier = Modifier.fillMaxWidth().padding(start = 16.dp, end = 16.dp, bottom = 16.dp),
                                    verticalArrangement = Arrangement.spacedBy(8.dp)
                                ) {
                                    HorizontalDivider(color = Color.White.copy(alpha = 0.08f))
                                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                        Text("Fairness Target Score:", color = Color.Gray, fontSize = 12.sp)
                                        Text("${diag.fairnessTarget}", color = NeonGreen, fontSize = 12.sp, fontWeight = FontWeight.Bold)
                                    }
                                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                        Text("Quality Gate Status:", color = Color.Gray, fontSize = 12.sp)
                                        Text(diag.qualityGateStatus, color = if (diag.qualityGateStatus == "BEST_AVAILABLE") GoldStar else NeonGreen, fontSize = 12.sp, fontWeight = FontWeight.Bold)
                                    }
                                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                        Text("Additional Generation Attempts:", color = Color.Gray, fontSize = 12.sp)
                                        Text("${diag.additionalAttempts}", color = Color.White, fontSize = 12.sp)
                                    }
                                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                        Text("Total Candidates Evaluated:", color = Color.Gray, fontSize = 12.sp)
                                        Text("${diag.candidatesGenerated}", color = Color.White, fontSize = 12.sp)
                                    }
                                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                        Text("Best Candidate Rank:", color = Color.Gray, fontSize = 12.sp)
                                        Text("${diag.bestCandidateRank}", color = Color.White, fontSize = 12.sp)
                                    }
                                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                        Text("Lowest Penalty Found:", color = Color.Gray, fontSize = 12.sp)
                                        Text("${diag.lowestPenaltyFound}", color = Color.White, fontSize = 12.sp)
                                    }
                                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                        Text("Highest Penalty Found:", color = Color.Gray, fontSize = 12.sp)
                                        Text("${diag.highestPenaltyFound}", color = Color.White, fontSize = 12.sp)
                                    }
                                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                        Text("Average Candidate Penalty:", color = Color.Gray, fontSize = 12.sp)
                                        Text(String.format("%.2f", diag.averageCandidatePenalty), color = Color.White, fontSize = 12.sp)
                                    }
                                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                        Text("Winning Candidate Penalty:", color = Color.Gray, fontSize = 12.sp)
                                        Text("${diag.winningCandidatePenalty}", color = Color.White, fontSize = 12.sp)
                                    }
                                    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                                        Text("Winning Candidate Fairness Score:", color = Color.Gray, fontSize = 12.sp)
                                        Text("${diag.winningCandidateFairnessScore}", color = Color.White, fontSize = 12.sp)
                                    }
                                    if (diag.failedCriteria.isNotEmpty()) {
                                        Column(modifier = Modifier.fillMaxWidth()) {
                                            Text("Failed Criteria:", color = GoldStar, fontSize = 12.sp, fontWeight = FontWeight.Bold)
                                            diag.failedCriteria.forEach { crit ->
                                                Text("• $crit", color = GoldStar, fontSize = 11.sp)
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            
            // Opponent Analysis Developer Debug Display
            if (currentShuffleNumber > 0 || opponentStats.uniquePairsCount > 0) {
                item {
                    GlassyCard(
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("opponent_pair_tracking_card"),
                        cornerRadius = 16
                    ) {
                        Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Icon(
                                        imageVector = Icons.Default.Person,
                                        contentDescription = "Opponent Pair Tracking",
                                        tint = FuchsiaAccent,
                                        modifier = Modifier.size(16.dp)
                                    )
                                    Spacer(modifier = Modifier.width(6.dp))
                                    Text(
                                        text = "Opponent Pair Tracking",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = FuchsiaAccent,
                                        fontWeight = FontWeight.Bold,
                                        letterSpacing = 1.sp
                                    )
                                }
                                Text(
                                    text = "DEV TRACKER",
                                    fontSize = 9.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = Color.LightGray,
                                    modifier = Modifier
                                        .clip(RoundedCornerShape(4.dp))
                                        .background(Color.White.copy(alpha = 0.1f))
                                        .padding(horizontal = 6.dp, vertical = 2.dp)
                                )
                            }
                            HorizontalDivider(color = Color.White.copy(alpha = 0.08f))

                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(vertical = 4.dp),
                                horizontalArrangement = Arrangement.SpaceEvenly,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                // Unique Opponent Pairs
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "${opponentStats.uniquePairsCount}",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = FuchsiaAccent,
                                        modifier = Modifier.testTag("unique_opponent_pairs")
                                    )
                                    Text(
                                        text = "Unique Opponents",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }
                                HorizontalDivider(
                                    modifier = Modifier
                                        .height(28.dp)
                                        .width(1.dp),
                                    color = Color.White.copy(alpha = 0.1f)
                                )
                                // Total Occurrences
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "${opponentStats.totalPairOccurrences}",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = FuchsiaAccent,
                                        modifier = Modifier.testTag("total_opponent_occurrences")
                                    )
                                    Text(
                                        text = "Total Encounters",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }
                            }
                            HorizontalDivider(color = Color.White.copy(alpha = 0.08f))
                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(vertical = 4.dp),
                                horizontalArrangement = Arrangement.SpaceEvenly,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                // Repeated Opponents
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "${opponentStats.repeatedPairOccurrences}",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = if (opponentStats.repeatedPairOccurrences > 0) FuchsiaAccent else Color.LightGray,
                                        modifier = Modifier.testTag("repeated_opponent_occurrences")
                                    )
                                    Text(
                                        text = "Repeated Opponents",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }
                                HorizontalDivider(
                                    modifier = Modifier
                                        .height(28.dp)
                                        .width(1.dp),
                                    color = Color.White.copy(alpha = 0.1f)
                                )
                                // Max Repeated Encounters
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "${opponentStats.maxRepeatedPairCount}×",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = if (opponentStats.maxRepeatedPairCount > 1) FuchsiaAccent else Color.LightGray,
                                        modifier = Modifier.testTag("max_repeated_opponent")
                                    )
                                    Text(
                                        text = "Most Repeated",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }
                            }
                        }
                    }
                }
            }

            // Teammate Pair Tracking Debug Display
            if (currentShuffleNumber > 0 || pairStats.uniquePairsCount > 0) {
                item {
                    GlassyCard(
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("teammate_pair_tracking_card"),
                        cornerRadius = 16
                    ) {
                        Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Icon(
                                        imageVector = Icons.Default.Person,
                                        contentDescription = "Teammate Pair Tracking",
                                        tint = GoldStar,
                                        modifier = Modifier.size(16.dp)
                                    )
                                    Spacer(modifier = Modifier.width(6.dp))
                                    Text(
                                        text = "Teammate Pair Tracking",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = GoldStar,
                                        fontWeight = FontWeight.Bold,
                                        letterSpacing = 1.sp
                                    )
                                }
                                Text(
                                    text = "DEV TRACKER",
                                    fontSize = 9.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = Color.LightGray,
                                    modifier = Modifier
                                        .clip(RoundedCornerShape(4.dp))
                                        .background(Color.White.copy(alpha = 0.1f))
                                        .padding(horizontal = 6.dp, vertical = 2.dp)
                                )
                            }

                            HorizontalDivider(color = Color.White.copy(alpha = 0.08f))

                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(vertical = 4.dp),
                                horizontalArrangement = Arrangement.SpaceEvenly,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                // Unique Pairs
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "${pairStats.uniquePairsCount}",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = Color.White,
                                        modifier = Modifier.testTag("unique_pairs_count")
                                    )
                                    Text(
                                        text = "Unique Pairs",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }

                                HorizontalDivider(
                                    modifier = Modifier
                                        .height(28.dp)
                                        .width(1.dp),
                                    color = Color.White.copy(alpha = 0.1f)
                                )

                                // Pair Occurrences
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "${pairStats.totalPairOccurrences}",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = NeonBlue,
                                        modifier = Modifier.testTag("pair_occurrences_count")
                                    )
                                    Text(
                                        text = "Pair Occurrences",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }

                                HorizontalDivider(
                                    modifier = Modifier
                                        .height(28.dp)
                                        .width(1.dp),
                                    color = Color.White.copy(alpha = 0.1f)
                                )

                                // Repeated Pair Occurrences
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "${pairStats.repeatedPairOccurrences}",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = if (pairStats.repeatedPairOccurrences > 0) GoldStar else Color.LightGray,
                                        modifier = Modifier.testTag("repeated_pair_occurrences_count")
                                    )
                                    Text(
                                        text = "Repeated Pair Occurrences",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }

                                HorizontalDivider(
                                    modifier = Modifier
                                        .height(28.dp)
                                        .width(1.dp),
                                    color = Color.White.copy(alpha = 0.1f)
                                )

                                // Most Repeated Pair Count
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "${pairStats.maxRepeatedPairCount}",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = if (pairStats.maxRepeatedPairCount > 1) FuchsiaAccent else Color.LightGray,
                                        modifier = Modifier.testTag("most_repeated_pair_count")
                                    )
                                    Text(
                                        text = "Most Repeated Pair Count",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }
                            }
                        }
                    }
                }
            }

            // Joker Rotation Section Display
            if (generatedTeams.isNotEmpty() || previousJokersHistory.isNotEmpty()) {
                item {
                    JokerRotationSection(
                        currentJoker = jokerPlayer,
                        remainingPlayers = remainingJokerCandidates,
                        previousJokers = previousJokersHistory,
                        onClearHistory = { viewModel.clearJokerHistory() }
                    )
                }
            }

            // Generated Teams List
            if (generatedTeams.isNotEmpty()) {
                item {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween,
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(top = 8.dp)
                    ) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(
                                imageVector = Icons.Default.Shuffle,
                                contentDescription = "Generated",
                                tint = NeonGreen,
                                modifier = Modifier.size(18.dp)
                            )
                            Spacer(modifier = Modifier.width(6.dp))
                            Text(
                                text = "BALANCED TEAMS",
                                style = MaterialTheme.typography.labelSmall,
                                color = NeonGreen,
                                fontWeight = FontWeight.Bold,
                                letterSpacing = 1.sp
                            )
                        }

                        Text(
                            text = "${generatedTeams.size} Teams Created",
                            style = MaterialTheme.typography.labelSmall,
                            color = Color.LightGray
                        )
                    }
                }

                items(generatedTeams.size, key = { generatedTeams[it].teamNumber }) { index ->
                    val team = generatedTeams[index]
                    val accentColor = when (index % 4) {
                        0 -> NeonGreen
                        1 -> NeonBlue
                        2 -> IndigoAccent
                        else -> GoldStar
                    }

                    GlassyCard(
                        modifier = Modifier.fillMaxWidth(),
                        cornerRadius = 20
                    ) {
                        Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween,
                                modifier = Modifier.fillMaxWidth()
                            ) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Box(
                                        modifier = Modifier
                                            .size(12.dp)
                                            .clip(RoundedCornerShape(4.dp))
                                            .background(accentColor)
                                    )
                                    Spacer(modifier = Modifier.width(8.dp))
                                    Text(
                                        text = team.name,
                                        style = MaterialTheme.typography.titleMedium.copy(
                                            fontWeight = FontWeight.Bold,
                                            color = Color.White
                                        )
                                    )
                                }

                                Box(
                                    modifier = Modifier
                                        .clip(RoundedCornerShape(8.dp))
                                        .background(accentColor.copy(alpha = 0.15f))
                                        .border(1.dp, accentColor.copy(alpha = 0.3f), RoundedCornerShape(8.dp))
                                        .padding(horizontal = 10.dp, vertical = 4.dp)
                                ) {
                                    Text(
                                        text = "${team.players.size} Players",
                                        color = accentColor,
                                        fontWeight = FontWeight.Bold,
                                        fontSize = 11.sp
                                    )
                                }
                            }

                            HorizontalDivider(color = Color.White.copy(alpha = 0.08f))

                            Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                                team.players.forEachIndexed { _, player ->
                                    Row(
                                        verticalAlignment = Alignment.CenterVertically,
                                        modifier = Modifier
                                            .fillMaxWidth()
                                            .clip(RoundedCornerShape(8.dp))
                                            .background(Color.White.copy(alpha = 0.03f))
                                            .padding(horizontal = 10.dp, vertical = 6.dp)
                                    ) {
                                        Icon(
                                            imageVector = Icons.Default.Person,
                                            contentDescription = "Player",
                                            tint = accentColor.copy(alpha = 0.7f),
                                            modifier = Modifier.size(14.dp)
                                        )
                                        Spacer(modifier = Modifier.width(8.dp))
                                        Text(
                                            text = player,
                                            color = Color.White,
                                            style = MaterialTheme.typography.bodyMedium,
                                            fontSize = 13.sp
                                        )
                                    }
                                }
                            }

                            if (team.totalStrength > 0) {
                                HorizontalDivider(color = Color.White.copy(alpha = 0.08f))
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    Text(
                                        text = "Team Strength: ${team.totalStrength}",
                                        color = NeonGreen,
                                        fontSize = 12.sp,
                                        fontWeight = FontWeight.Bold
                                    )
                                    Text(
                                        text = "Avg Rating: ${String.format(java.util.Locale.US, "%.2f", team.averageStrength)}",
                                        color = NeonBlue,
                                        fontSize = 12.sp,
                                        fontWeight = FontWeight.Medium
                                    )
                                }
                            }
                        }
                    }
                }
            }

            // In-Memory Session History Section
            if (sessionHistory.isNotEmpty()) {
                item {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween,
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(top = 12.dp)
                    ) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(
                                imageVector = Icons.Default.History,
                                contentDescription = "Session History",
                                tint = GoldStar,
                                modifier = Modifier.size(18.dp)
                            )
                            Spacer(modifier = Modifier.width(6.dp))
                            Text(
                                text = "SESSION SHUFFLE HISTORY",
                                style = MaterialTheme.typography.labelSmall,
                                color = GoldStar,
                                fontWeight = FontWeight.Bold,
                                letterSpacing = 1.sp
                            )
                        }

                        Text(
                            text = "${sessionHistory.size} Shuffles Saved",
                            style = MaterialTheme.typography.labelSmall,
                            color = Color.LightGray
                        )
                    }
                }

                items(sessionHistory.size, key = { "session_${sessionHistory[it].shuffleNumber}" }) { index ->
                    val session = sessionHistory[index]
                    val timeFormat = remember { SimpleDateFormat("hh:mm:ss a", Locale.getDefault()) }

                    GlassyCard(
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("session_history_card_${session.shuffleNumber}"),
                        cornerRadius = 20
                    ) {
                        Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween,
                                modifier = Modifier.fillMaxWidth()
                            ) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Box(
                                        modifier = Modifier
                                            .clip(RoundedCornerShape(8.dp))
                                            .background(GoldStar.copy(alpha = 0.15f))
                                            .border(1.dp, GoldStar.copy(alpha = 0.3f), RoundedCornerShape(8.dp))
                                            .padding(horizontal = 10.dp, vertical = 4.dp)
                                    ) {
                                        Text(
                                            text = "Shuffle #${session.shuffleNumber}",
                                            color = GoldStar,
                                            fontWeight = FontWeight.Bold,
                                            fontSize = 11.sp
                                        )
                                    }
                                    Spacer(modifier = Modifier.width(8.dp))
                                    Text(
                                        text = "${session.players.size} Players",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.LightGray
                                    )
                                }

                                Text(
                                    text = timeFormat.format(Date(session.timestamp)),
                                    style = MaterialTheme.typography.labelSmall,
                                    color = Color.Gray
                                )
                            }

                            HorizontalDivider(color = Color.White.copy(alpha = 0.08f))

                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Icon(
                                    imageVector = Icons.Default.AutoAwesome,
                                    contentDescription = "Joker",
                                    tint = if (session.joker != null) FuchsiaAccent else NeonBlue,
                                    modifier = Modifier.size(14.dp)
                                )
                                Spacer(modifier = Modifier.width(6.dp))
                                Text(
                                    text = if (session.joker != null) "Joker: ${session.joker}" else "Joker: None (Even Split)",
                                    color = if (session.joker != null) FuchsiaAccent else Color.LightGray,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 12.sp
                                )
                            }

                            Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                                session.teams.forEach { team ->
                                    Row(
                                        verticalAlignment = Alignment.CenterVertically,
                                        modifier = Modifier
                                            .fillMaxWidth()
                                            .clip(RoundedCornerShape(6.dp))
                                            .background(Color.White.copy(alpha = 0.03f))
                                            .padding(horizontal = 8.dp, vertical = 4.dp)
                                    ) {
                                        Text(
                                            text = "${team.name}: ",
                                            color = NeonGreen,
                                            fontWeight = FontWeight.Bold,
                                            fontSize = 12.sp
                                        )
                                        Text(
                                            text = team.players.joinToString(", "),
                                            color = Color.White,
                                            fontSize = 12.sp
                                        )
                                    }
                                }
                            }
                        }
                    }
                }
            }

            item {
                Spacer(modifier = Modifier.height(100.dp))
            }
        }
    }
}
