package com.example.ui.screens

import androidx.compose.animation.*
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.History
import androidx.compose.material.icons.filled.Group
import androidx.compose.material.icons.filled.Warning
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.Shuffle
import androidx.compose.material.icons.filled.Person
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.ui.components.FrostedMeshBackground
import com.example.ui.components.GlassyCard
import com.example.ui.components.JokerCard
import com.example.ui.components.JokerRotationSection
import com.example.ui.components.NeonButton
import com.example.ui.theme.CrimsonHot
import com.example.ui.theme.FuchsiaAccent
import com.example.ui.theme.GoldStar
import com.example.ui.theme.IndigoAccent
import com.example.ui.theme.NeonBlue
import com.example.ui.theme.NeonGreen
import com.example.ui.viewmodel.AppViewModel
import java.text.SimpleDateFormat
import java.util.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TeamConfigScreen(viewModel: AppViewModel) {
    val numberOfTeams by viewModel.configNumberOfTeams.collectAsState()
    val configState by viewModel.teamConfigState.collectAsState()
    val playersList by viewModel.buildPlayersList.collectAsState()
    val generatedTeams by viewModel.generatedTeams.collectAsState()
    val jokerPlayer by viewModel.jokerPlayer.collectAsState()
    val remainingJokerCandidates by viewModel.remainingJokerCandidates.collectAsState()
    val previousJokersHistory by viewModel.previousJokersHistory.collectAsState()
    val sessionHistory by viewModel.sessionHistory.collectAsState()
    val uniqueTeamsGenerated by viewModel.uniqueTeamsGenerated.collectAsState()
    val duplicatesPrevented by viewModel.duplicatesPrevented.collectAsState()
    val currentShuffleNumber by viewModel.currentShuffleNumber.collectAsState()
    val pairStats by viewModel.pairStatistics.collectAsState()

    FrostedMeshBackground {
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(horizontal = 20.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            item {
                Spacer(modifier = Modifier.height(24.dp))
                Text(
                    text = "TEAM CONFIGURATION",
                    style = MaterialTheme.typography.titleSmall.copy(
                        color = IndigoAccent,
                        fontWeight = FontWeight.Bold,
                        letterSpacing = 2.sp
                    )
                )
                Text(
                    text = "Configure how your active roster is divided",
                    style = MaterialTheme.typography.bodySmall,
                    color = Color.LightGray
                )
                Spacer(modifier = Modifier.height(8.dp))
            }

            // Number of Teams Input Card
            item {
                GlassyCard(
                    modifier = Modifier.fillMaxWidth(),
                    cornerRadius = 24
                ) {
                    Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.SpaceBetween,
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Icon(
                                    imageVector = Icons.Default.Group,
                                    contentDescription = "Teams",
                                    tint = IndigoAccent,
                                    modifier = Modifier.size(24.dp)
                                )
                                Spacer(modifier = Modifier.width(8.dp))
                                Text(
                                    text = "Split Roster Into",
                                    style = MaterialTheme.typography.titleMedium.copy(
                                        fontWeight = FontWeight.Bold,
                                        color = Color.White
                                    )
                                )
                            }
                            
                            // Active Players Badge
                            Box(
                                modifier = Modifier
                                    .clip(RoundedCornerShape(8.dp))
                                    .background(NeonBlue.copy(alpha = 0.15f))
                                    .border(1.dp, NeonBlue.copy(alpha = 0.3f), RoundedCornerShape(8.dp))
                                    .padding(horizontal = 10.dp, vertical = 6.dp)
                            ) {
                                Text(
                                    text = "${playersList.size} Active Players",
                                    color = NeonBlue,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 12.sp
                                )
                            }
                        }

                        Divider(color = Color.White.copy(alpha = 0.08f))

                        OutlinedTextField(
                            value = numberOfTeams,
                            onValueChange = { viewModel.updateConfigNumberOfTeams(it) },
                            label = { Text("Number of Teams") },
                            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                            colors = OutlinedTextFieldDefaults.colors(
                                focusedTextColor = Color.White,
                                unfocusedTextColor = Color.White,
                                focusedBorderColor = IndigoAccent,
                                unfocusedBorderColor = Color.White.copy(alpha = 0.12f),
                                focusedLabelColor = IndigoAccent,
                                unfocusedLabelColor = Color.Gray
                            ),
                            modifier = Modifier.fillMaxWidth().testTag("number_of_teams_input"),
                            singleLine = true
                        )
                    }
                }
            }

            // Calculation Preview Card
            item {
                GlassyCard(
                    modifier = Modifier.fillMaxWidth(),
                    cornerRadius = 24
                ) {
                    Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
                        Text(
                            text = "PREVIEW",
                            style = MaterialTheme.typography.labelSmall,
                            color = Color.Gray,
                            fontWeight = FontWeight.Bold
                        )

                        AnimatedVisibility(
                            visible = configState.error != null,
                            enter = fadeIn() + expandVertically(),
                            exit = fadeOut() + shrinkVertically()
                        ) {
                            Box(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .clip(RoundedCornerShape(12.dp))
                                    .background(CrimsonHot.copy(alpha = 0.1f))
                                    .border(1.dp, CrimsonHot.copy(alpha = 0.3f), RoundedCornerShape(12.dp))
                                    .padding(16.dp)
                            ) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Icon(
                                        imageVector = Icons.Default.Warning,
                                        contentDescription = "Error",
                                        tint = CrimsonHot
                                    )
                                    Spacer(modifier = Modifier.width(12.dp))
                                    Text(
                                        text = configState.error ?: "",
                                        color = CrimsonHot,
                                        style = MaterialTheme.typography.bodyMedium,
                                        fontWeight = FontWeight.Bold
                                    )
                                }
                            }
                        }

                        AnimatedVisibility(
                            visible = configState.error == null,
                            enter = fadeIn() + expandVertically(),
                            exit = fadeOut() + shrinkVertically()
                        ) {
                            Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                                // Players per team
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .clip(RoundedCornerShape(12.dp))
                                        .background(NeonGreen.copy(alpha = 0.05f))
                                        .border(1.dp, NeonGreen.copy(alpha = 0.2f), RoundedCornerShape(12.dp))
                                        .padding(16.dp)
                                ) {
                                    Row(verticalAlignment = Alignment.CenterVertically) {
                                        Icon(Icons.Default.Info, contentDescription = "Info", tint = NeonGreen)
                                        Spacer(modifier = Modifier.width(12.dp))
                                        Text(
                                            text = "Players Per Team",
                                            color = Color.LightGray,
                                            style = MaterialTheme.typography.bodyMedium
                                        )
                                    }
                                    Text(
                                        text = "${configState.playersPerTeam}",
                                        color = NeonGreen,
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold
                                    )
                                }

                                // Remaining Players
                                Row(
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .clip(RoundedCornerShape(12.dp))
                                        .background(if (configState.remainingPlayers > 0) GoldStar.copy(alpha = 0.05f) else Color.White.copy(alpha = 0.02f))
                                        .border(1.dp, if (configState.remainingPlayers > 0) GoldStar.copy(alpha = 0.2f) else Color.White.copy(alpha = 0.05f), RoundedCornerShape(12.dp))
                                        .padding(16.dp)
                                ) {
                                    Row(verticalAlignment = Alignment.CenterVertically) {
                                        Icon(
                                            Icons.Default.Info, 
                                            contentDescription = "Info", 
                                            tint = if (configState.remainingPlayers > 0) GoldStar else Color.Gray
                                        )
                                        Spacer(modifier = Modifier.width(12.dp))
                                        Text(
                                            text = "Remaining Substitutes",
                                            color = Color.LightGray,
                                            style = MaterialTheme.typography.bodyMedium
                                        )
                                    }
                                    Text(
                                        text = "${configState.remainingPlayers}",
                                        color = if (configState.remainingPlayers > 0) GoldStar else Color.Gray,
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold
                                    )
                                }
                            }
                        }
                    }
                }
            }

            // Shuffle Button Item
            item {
                AnimatedVisibility(
                    visible = configState.error == null,
                    enter = fadeIn() + expandVertically(),
                    exit = fadeOut() + shrinkVertically()
                ) {
                    NeonButton(
                        text = if (generatedTeams.isEmpty()) "Shuffle & Generate Teams" else "Shuffle Again",
                        onClick = { viewModel.shuffleTeams() },
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("shuffle_again_button"),
                        glowingColor = NeonGreen
                    )
                }
            }

            // Duplicate Detection & Shuffle Stats Display
            if (currentShuffleNumber > 0 || uniqueTeamsGenerated > 0 || duplicatesPrevented > 0) {
                item {
                    GlassyCard(
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("shuffle_stats_card"),
                        cornerRadius = 16
                    ) {
                        Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(vertical = 4.dp),
                                horizontalArrangement = Arrangement.SpaceEvenly,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                // Current Shuffle Number
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = if (currentShuffleNumber > 0) "#$currentShuffleNumber" else "-",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = NeonGreen,
                                        modifier = Modifier.testTag("current_shuffle_number")
                                    )
                                    Text(
                                        text = "Current Shuffle",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }

                                Divider(
                                    modifier = Modifier
                                        .height(28.dp)
                                        .width(1.dp),
                                    color = Color.White.copy(alpha = 0.1f)
                                )

                                // Unique Teams Generated
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "$uniqueTeamsGenerated",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = NeonBlue,
                                        modifier = Modifier.testTag("unique_teams_generated")
                                    )
                                    Text(
                                        text = "Unique Teams",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }

                                Divider(
                                    modifier = Modifier
                                        .height(28.dp)
                                        .width(1.dp),
                                    color = Color.White.copy(alpha = 0.1f)
                                )

                                // Duplicate Prevented
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "$duplicatesPrevented",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = if (duplicatesPrevented > 0) GoldStar else Color.LightGray,
                                        modifier = Modifier.testTag("duplicate_prevented")
                                    )
                                    Text(
                                        text = "Duplicate Prevented",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }
                            }

                            if (duplicatesPrevented > 0) {
                                Row(
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .clip(RoundedCornerShape(8.dp))
                                        .background(GoldStar.copy(alpha = 0.12f))
                                        .padding(horizontal = 10.dp, vertical = 6.dp),
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.Center
                                ) {
                                    Icon(
                                        imageVector = Icons.Default.Warning,
                                        contentDescription = "Duplicate Prevented",
                                        tint = GoldStar,
                                        modifier = Modifier.size(14.dp)
                                    )
                                    Spacer(modifier = Modifier.width(6.dp))
                                    Text(
                                        text = "Duplicate Prevented ($duplicatesPrevented detected)",
                                        color = GoldStar,
                                        fontSize = 11.sp,
                                        fontWeight = FontWeight.SemiBold
                                    )
                                }
                            }
                        }
                    }
                }
            }

            // Teammate Pair Tracking Debug Display
            if (currentShuffleNumber > 0 || pairStats.uniquePairsCount > 0) {
                item {
                    GlassyCard(
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("teammate_pair_tracking_card"),
                        cornerRadius = 16
                    ) {
                        Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                            Row(
                                modifier = Modifier.fillMaxWidth(),
                                horizontalArrangement = Arrangement.SpaceBetween,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Icon(
                                        imageVector = Icons.Default.Group,
                                        contentDescription = "Teammate Pair Tracking",
                                        tint = GoldStar,
                                        modifier = Modifier.size(16.dp)
                                    )
                                    Spacer(modifier = Modifier.width(6.dp))
                                    Text(
                                        text = "Teammate Pair Tracking",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = GoldStar,
                                        fontWeight = FontWeight.Bold,
                                        letterSpacing = 1.sp
                                    )
                                }
                                Text(
                                    text = "DEV TRACKER",
                                    fontSize = 9.sp,
                                    fontWeight = FontWeight.Bold,
                                    color = Color.LightGray,
                                    modifier = Modifier
                                        .clip(RoundedCornerShape(4.dp))
                                        .background(Color.White.copy(alpha = 0.1f))
                                        .padding(horizontal = 6.dp, vertical = 2.dp)
                                )
                            }

                            Divider(color = Color.White.copy(alpha = 0.08f))

                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(vertical = 4.dp),
                                horizontalArrangement = Arrangement.SpaceEvenly,
                                verticalAlignment = Alignment.CenterVertically
                            ) {
                                // Unique Pairs
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "${pairStats.uniquePairsCount}",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = Color.White,
                                        modifier = Modifier.testTag("unique_pairs_count")
                                    )
                                    Text(
                                        text = "Unique Pairs",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }

                                Divider(
                                    modifier = Modifier
                                        .height(28.dp)
                                        .width(1.dp),
                                    color = Color.White.copy(alpha = 0.1f)
                                )

                                // Pair Occurrences
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "${pairStats.totalPairOccurrences}",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = NeonBlue,
                                        modifier = Modifier.testTag("pair_occurrences_count")
                                    )
                                    Text(
                                        text = "Pair Occurrences",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }

                                Divider(
                                    modifier = Modifier
                                        .height(28.dp)
                                        .width(1.dp),
                                    color = Color.White.copy(alpha = 0.1f)
                                )

                                // Repeated Pair Occurrences
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "${pairStats.repeatedPairOccurrences}",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = if (pairStats.repeatedPairOccurrences > 0) GoldStar else Color.LightGray,
                                        modifier = Modifier.testTag("repeated_pair_occurrences_count")
                                    )
                                    Text(
                                        text = "Repeated Pair Occurrences",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }

                                Divider(
                                    modifier = Modifier
                                        .height(28.dp)
                                        .width(1.dp),
                                    color = Color.White.copy(alpha = 0.1f)
                                )

                                // Most Repeated Pair Count
                                Column(
                                    horizontalAlignment = Alignment.CenterHorizontally,
                                    verticalArrangement = Arrangement.spacedBy(2.dp)
                                ) {
                                    Text(
                                        text = "${pairStats.maxRepeatedPairCount}",
                                        style = MaterialTheme.typography.titleMedium,
                                        fontWeight = FontWeight.Bold,
                                        color = if (pairStats.maxRepeatedPairCount > 1) FuchsiaAccent else Color.LightGray,
                                        modifier = Modifier.testTag("most_repeated_pair_count")
                                    )
                                    Text(
                                        text = "Most Repeated Pair Count",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.Gray,
                                        fontSize = 10.sp
                                    )
                                }
                            }
                        }
                    }
                }
            }

            // Joker Rotation Section Display
            if (generatedTeams.isNotEmpty() || previousJokersHistory.isNotEmpty()) {
                item {
                    JokerRotationSection(
                        currentJoker = jokerPlayer,
                        remainingPlayers = remainingJokerCandidates,
                        previousJokers = previousJokersHistory,
                        onClearHistory = { viewModel.clearJokerHistory() }
                    )
                }
            }

            // Generated Teams List
            if (generatedTeams.isNotEmpty()) {
                item {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween,
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(top = 8.dp)
                    ) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(
                                imageVector = Icons.Default.Shuffle,
                                contentDescription = "Generated",
                                tint = NeonGreen,
                                modifier = Modifier.size(18.dp)
                            )
                            Spacer(modifier = Modifier.width(6.dp))
                            Text(
                                text = "BALANCED TEAMS",
                                style = MaterialTheme.typography.labelSmall,
                                color = NeonGreen,
                                fontWeight = FontWeight.Bold,
                                letterSpacing = 1.sp
                            )
                        }

                        Text(
                            text = "${generatedTeams.size} Teams Created",
                            style = MaterialTheme.typography.labelSmall,
                            color = Color.LightGray
                        )
                    }
                }

                items(generatedTeams.size, key = { generatedTeams[it].teamNumber }) { index ->
                    val team = generatedTeams[index]
                    val accentColor = when (index % 4) {
                        0 -> NeonGreen
                        1 -> NeonBlue
                        2 -> IndigoAccent
                        else -> GoldStar
                    }

                    GlassyCard(
                        modifier = Modifier.fillMaxWidth(),
                        cornerRadius = 20
                    ) {
                        Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween,
                                modifier = Modifier.fillMaxWidth()
                            ) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Box(
                                        modifier = Modifier
                                            .size(12.dp)
                                            .clip(RoundedCornerShape(4.dp))
                                            .background(accentColor)
                                    )
                                    Spacer(modifier = Modifier.width(8.dp))
                                    Text(
                                        text = team.name,
                                        style = MaterialTheme.typography.titleMedium.copy(
                                            fontWeight = FontWeight.Bold,
                                            color = Color.White
                                        )
                                    )
                                }

                                Box(
                                    modifier = Modifier
                                        .clip(RoundedCornerShape(8.dp))
                                        .background(accentColor.copy(alpha = 0.15f))
                                        .border(1.dp, accentColor.copy(alpha = 0.3f), RoundedCornerShape(8.dp))
                                        .padding(horizontal = 10.dp, vertical = 4.dp)
                                ) {
                                    Text(
                                        text = "${team.players.size} Players",
                                        color = accentColor,
                                        fontWeight = FontWeight.Bold,
                                        fontSize = 11.sp
                                    )
                                }
                            }

                            Divider(color = Color.White.copy(alpha = 0.08f))

                            Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                                team.players.forEachIndexed { _, player ->
                                    Row(
                                        verticalAlignment = Alignment.CenterVertically,
                                        modifier = Modifier
                                            .fillMaxWidth()
                                            .clip(RoundedCornerShape(8.dp))
                                            .background(Color.White.copy(alpha = 0.03f))
                                            .padding(horizontal = 10.dp, vertical = 6.dp)
                                    ) {
                                        Icon(
                                            imageVector = Icons.Default.Person,
                                            contentDescription = "Player",
                                            tint = accentColor.copy(alpha = 0.7f),
                                            modifier = Modifier.size(14.dp)
                                        )
                                        Spacer(modifier = Modifier.width(8.dp))
                                        Text(
                                            text = player,
                                            color = Color.White,
                                            style = MaterialTheme.typography.bodyMedium,
                                            fontSize = 13.sp
                                        )
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // In-Memory Session History Section
            if (sessionHistory.isNotEmpty()) {
                item {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.SpaceBetween,
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(top = 12.dp)
                    ) {
                        Row(verticalAlignment = Alignment.CenterVertically) {
                            Icon(
                                imageVector = Icons.Default.History,
                                contentDescription = "Session History",
                                tint = GoldStar,
                                modifier = Modifier.size(18.dp)
                            )
                            Spacer(modifier = Modifier.width(6.dp))
                            Text(
                                text = "SESSION SHUFFLE HISTORY",
                                style = MaterialTheme.typography.labelSmall,
                                color = GoldStar,
                                fontWeight = FontWeight.Bold,
                                letterSpacing = 1.sp
                            )
                        }

                        Text(
                            text = "${sessionHistory.size} Shuffles Saved",
                            style = MaterialTheme.typography.labelSmall,
                            color = Color.LightGray
                        )
                    }
                }

                items(sessionHistory.size, key = { "session_${sessionHistory[it].shuffleNumber}" }) { index ->
                    val session = sessionHistory[index]
                    val timeFormat = remember { SimpleDateFormat("hh:mm:ss a", Locale.getDefault()) }

                    GlassyCard(
                        modifier = Modifier
                            .fillMaxWidth()
                            .testTag("session_history_card_${session.shuffleNumber}"),
                        cornerRadius = 20
                    ) {
                        Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                horizontalArrangement = Arrangement.SpaceBetween,
                                modifier = Modifier.fillMaxWidth()
                            ) {
                                Row(verticalAlignment = Alignment.CenterVertically) {
                                    Box(
                                        modifier = Modifier
                                            .clip(RoundedCornerShape(8.dp))
                                            .background(GoldStar.copy(alpha = 0.15f))
                                            .border(1.dp, GoldStar.copy(alpha = 0.3f), RoundedCornerShape(8.dp))
                                            .padding(horizontal = 10.dp, vertical = 4.dp)
                                    ) {
                                        Text(
                                            text = "Shuffle #${session.shuffleNumber}",
                                            color = GoldStar,
                                            fontWeight = FontWeight.Bold,
                                            fontSize = 11.sp
                                        )
                                    }
                                    Spacer(modifier = Modifier.width(8.dp))
                                    Text(
                                        text = "${session.players.size} Players",
                                        style = MaterialTheme.typography.labelSmall,
                                        color = Color.LightGray
                                    )
                                }

                                Text(
                                    text = timeFormat.format(Date(session.timestamp)),
                                    style = MaterialTheme.typography.labelSmall,
                                    color = Color.Gray
                                )
                            }

                            Divider(color = Color.White.copy(alpha = 0.08f))

                            Row(verticalAlignment = Alignment.CenterVertically) {
                                Icon(
                                    imageVector = Icons.Default.AutoAwesome,
                                    contentDescription = "Joker",
                                    tint = if (session.joker != null) FuchsiaAccent else NeonBlue,
                                    modifier = Modifier.size(14.dp)
                                )
                                Spacer(modifier = Modifier.width(6.dp))
                                Text(
                                    text = if (session.joker != null) "Joker: ${session.joker}" else "Joker: None (Even Split)",
                                    color = if (session.joker != null) FuchsiaAccent else Color.LightGray,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 12.sp
                                )
                            }

                            Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                                session.teams.forEach { team ->
                                    Row(
                                        verticalAlignment = Alignment.CenterVertically,
                                        modifier = Modifier
                                            .fillMaxWidth()
                                            .clip(RoundedCornerShape(6.dp))
                                            .background(Color.White.copy(alpha = 0.03f))
                                            .padding(horizontal = 8.dp, vertical = 4.dp)
                                    ) {
                                        Text(
                                            text = "${team.name}: ",
                                            color = NeonGreen,
                                            fontWeight = FontWeight.Bold,
                                            fontSize = 12.sp
                                        )
                                        Text(
                                            text = team.players.joinToString(", "),
                                            color = Color.White,
                                            fontSize = 12.sp
                                        )
                                    }
                                }
                            }
                        }
                    }
                }
            }

            item {
                Spacer(modifier = Modifier.height(100.dp))
            }
        }
    }
}
